Docker: Lots of issues with the image, no need for named volume anymore
- adjusted rclone.conf path to make a plain bind mount work, so a named
volume no longer needed
- it is now required to provide RCLONE_USER/RCLONE_PASS credentials
- rclone rcd arguments were unquoted (breaking on empty values and spaces)
- rclone rcd is run with exec to make it PID 1, otherwise it got SIGKILL'ed
instead of SIGTERM on stopping the container
- the base image was unpinned (alpine:latest)
- incorrect RUN layers (such as an entire RUN being just cd /tmp)
- catching errors in scripts to explicitly fail the process
- incorrect shebangs in scripts
- updated instructions

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,15 +1,20 @@
 # could have used https://rclone.org/install/#docker as the base image
 # (and probably should)
-FROM alpine:latest
+FROM alpine:3.22
 
-RUN apk add --no-cache tzdata
+# `amd64`, `arm64`, etc - is set by `buildx`, which means that the image requires
+# BuildKit, which is default for `docker build` since Docker v23, but it can be
+# disabled with `DOCKER_BUILDKIT=0`, and then `TARGETARCH` would be empty
+# (and that wiil fail the rclone download below)
+ARG TARGETARCH
+# if we ever need `linux-arm-v7`, `linux-arm-v6` and so on
+#ARG TARGETVARIANT
 
-# RCLONE_VERSION seems to be used by rclone, so it's better not to export it,
-# although it is not(?) an environment variable here, so it wouldn't hurt anyway
-ARG RCLONE_VERSION_VALUE="v1.68.2"
+ARG RCLONE_VERSION_VALUE="v1.75.0"
+
 # not sure, but looks like these can't really be exposed as ENV for user to override
-ARG USER="rclone"
-ARG GROUPNAME="$USER"
+ARG APPLICATION_USER="rclone"
+ARG APPLICATION_GROUP="$APPLICATION_USER"
 ARG UID="1000"
 ARG GID="1000"
 
@@ -19,10 +24,20 @@ ARG GID="1000"
 #
 ENV PATH_TO_WEB_GUI="/var/www/rclone-rc-web-gui"
 ENV RCLONE_PORT="5572"
+# this one is an actual rclone variable (--config) and it is set explicitly so that
+# rclone doesn't have to resolve $HOME to find the config, which is also what allows
+# running the container as an arbitrary user (`docker run --user 1027:100`) when
+# mounted folders on host are owned by someone other than the UID below
+#
+# `/config` is meant to be mounted, so the default config can not be baked in here,
+# and it is `entrypoint.sh` who creates the initial config on the first ever start
+# (same way as with `settings.js`)
+ENV RCLONE_CONFIG="/config/rclone.conf"
 #
 # - these are for overriding
 #
-# had to split it into scheme and address because of sed stumbling upon `//`
+# had to split it into scheme and address because of sed stumbling upon `//`,
+# also actually `sed -e "s|...|...|"` should take any delimiter, so it might work
 ENV RCLONE_ALLOW_ORIGIN_SCHEME="http"
 ENV RCLONE_ALLOW_ORIGIN_HOST="localhost"
 # the `RCLONE_PORT` is for `rclone rcd` inside the container,
@@ -30,47 +45,57 @@ ENV RCLONE_ALLOW_ORIGIN_HOST="localhost"
 # mapped on the host at the public interface, as they are likely
 # to be different and only the public one matters for CORS
 ENV RCLONE_ALLOW_ORIGIN_PORT="5572"
-ENV RCLONE_USER="rclone"
-ENV RCLONE_PASS="enolcr"
+# no hardcoded credentials, because anyone can read ENV defaults from the image,
+# so instead it's the `entrypoint.sh` who will refuse to start rclone if these are not set
+ENV RCLONE_USER=""
+ENV RCLONE_PASS=""
 
-#WORKDIR $PATH_TO_WEB_GUI
-#ADD contents.tar ./
+# several related operations in one layer, using absolute paths instead of `~`
+# and short BusyBox flags instead of GNU-style long ones (BusyBox does support
+# `adduser`/`addgroup` but via an optional table, so short variants are somewhat safer)
+#
+# the config folder is created (and chown'ed) empty (without a config file inside)
+RUN set -eux; \
+    apk add --no-cache tzdata; \
+    addgroup -g "$GID" "$APPLICATION_GROUP"; \
+    adduser -D -H -g "" -G "$APPLICATION_GROUP" -u "$UID" -h "/home/$APPLICATION_USER" "$APPLICATION_USER"; \
+    mkdir -p "/home/$APPLICATION_USER/.ssh" "$(dirname "$RCLONE_CONFIG")" /data "$PATH_TO_WEB_GUI"; \
+    chmod 0700 "/home/$APPLICATION_USER/.ssh"; \
+    chown -R "$UID:$GID" "/home/$APPLICATION_USER" "$(dirname "$RCLONE_CONFIG")" /data "$PATH_TO_WEB_GUI"
 
-RUN mkdir -p $PATH_TO_WEB_GUI
-ADD contents.tar $PATH_TO_WEB_GUI/
+# this goes before `contents.tar`, because archive tend to change more often than
+# the rclone version, and so editing the web UI part would not re-download rclone
+#
+# the checksum is fetched over the same channel as the archive itself, so it can only
+# be used to prove the integrity of the download, not its authenticity. We could use
+# the PGP signature, but that's a `gnupg` dependency plus a PGP key fingerprint to handle
+RUN set -eux; \
+    cd /tmp; \
+    RCLONE_DIR="rclone-${RCLONE_VERSION_VALUE}-linux-${TARGETARCH}"; \
+    wget -q "https://downloads.rclone.org/${RCLONE_VERSION_VALUE}/${RCLONE_DIR}.zip"; \
+    wget -q "https://downloads.rclone.org/${RCLONE_VERSION_VALUE}/SHA256SUMS"; \
+    grep -F "${RCLONE_DIR}.zip" SHA256SUMS > expected-checksum.txt; \
+    [ -s expected-checksum.txt ]; \
+    sha256sum -c expected-checksum.txt; \
+    unzip -j "${RCLONE_DIR}.zip" "${RCLONE_DIR}/rclone" -d /usr/local/bin; \
+    chmod 0755 /usr/local/bin/rclone; \
+    rm -f "${RCLONE_DIR}.zip" SHA256SUMS expected-checksum.txt; \
+    rclone --version
 
 # only by utilizing a script in ENTRYPOINT one can use the ENV variables
 # to let user override those values
-COPY entrypoint.sh /
+COPY --chmod=0755 entrypoint.sh /entrypoint.sh
 
-RUN mkdir /data
+# `ADD` both extracts the tar and sets ownership in a single layer,
+# so there is no `chown -R` afterwards rewriting every file into a second copy
+ADD --chown=$UID:$GID contents.tar $PATH_TO_WEB_GUI/
 
-RUN cd /tmp
-RUN wget https://downloads.rclone.org/${RCLONE_VERSION_VALUE}/rclone-${RCLONE_VERSION_VALUE}-linux-amd64.zip
-RUN unzip -j "./rclone-${RCLONE_VERSION_VALUE}-linux-amd64.zip" "rclone-${RCLONE_VERSION_VALUE}-linux-amd64/rclone" -d "/bin"
-RUN rm ./rclone-${RCLONE_VERSION_VALUE}-linux-amd64.zip
-
-RUN addgroup \
-    --gid $GID \
-    $GROUPNAME \
-    && adduser \
-        --disabled-password \
-        --gecos "" \
-        --ingroup $GROUPNAME \
-        --uid $UID \
-        $USER
-RUN chown -R $USER:$GROUPNAME $PATH_TO_WEB_GUI /data
-
-USER $USER
-
-RUN mkdir ~/.ssh
-
-# not needed really, but it is useful to explicitly check
-# that rclone can run at all
-RUN rclone --version
-
-RUN printf "[disk]\ntype = alias\nremote = /data\n" > ~/.config/rclone/rclone.conf
+USER $APPLICATION_USER
+WORKDIR /data
 
 EXPOSE $RCLONE_PORT
 
+# entrypoint.sh finishes with `exec rclone rcd ...`, which replaces this shell,
+# so that rclone becomes PID 1 itself and receives the SIGTERM from `docker stop`
+# instead of being SIGKILL'ed after the timeout
 ENTRYPOINT [ "/bin/sh", "/entrypoint.sh" ]
